name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install required packages
        run: apt-get update && apt-get install -y git sudo
      - name: Install dotfiles
        run: .bin/install.sh
  amazonlinux2:
    runs-on: ubuntu-latest
    container: amazonlinux:2
    steps:
      - uses: actions/checkout@v1
      - name: Install required packages
        run: yum install -y git sudo
      - name: Install dotfiles
        run: .bin/install.sh
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dotfiles
        run: ./bin/install.sh
